# Generated by Django 5.1.6 on 2025-02-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_remove_task_is_completed_inquiry_user_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
